// <auto-generated />
using System;
using BulkingPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BulkingPro.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BulkingPro.Models.AgendamentoAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<int>("HorarioTrabalhoId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("HorarioTrabalhoId");

                    b.HasIndex("PersonalId");

                    b.ToTable("AgendamentosAlunos");
                });

            modelBuilder.Entity("BulkingPro.Models.AlunoHorarioAtendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("PersonalId", "DiaSemana", "HoraInicio", "HoraFim")
                        .IsUnique()
                        .HasDatabaseName("IX_AlunoHorarioAtendimento_Unique");

                    b.ToTable("AlunosHorariosAtendimento");
                });

            modelBuilder.Entity("BulkingPro.Models.AnamneseAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConsomeAlcool")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FazDieta")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FezCirurgia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FrequenciaSemanal")
                        .HasColumnType("longtext");

                    b.Property<bool>("Fuma")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("JaTreinouAntes")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Objetivo")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacoesGerais")
                        .HasColumnType("longtext");

                    b.Property<string>("QualCirurgia")
                        .HasColumnType("longtext");

                    b.Property<string>("QualDoenca")
                        .HasColumnType("longtext");

                    b.Property<string>("QualDor")
                        .HasColumnType("longtext");

                    b.Property<string>("QualLimitacao")
                        .HasColumnType("longtext");

                    b.Property<string>("QualMedicamento")
                        .HasColumnType("longtext");

                    b.Property<bool>("TemDoenca")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TemDorMovimento")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("TemLimitacaoMovimento")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TempoPorDia")
                        .HasColumnType("longtext");

                    b.Property<string>("TempoSemAtividade")
                        .HasColumnType("longtext");

                    b.Property<string>("TempoTreinando")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoDieta")
                        .HasColumnType("longtext");

                    b.Property<string>("TreinadorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("UsaMedicamento")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinadorId");

                    b.ToTable("Anamneses");
                });

            modelBuilder.Entity("BulkingPro.Models.AvaliacaoFisica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Abdomen")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("BicepsDireito")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("BicepsEsquerdo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Cintura")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("CoxaDireita")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("CoxaEsquerda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Ombro")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PanturrilhaDireita")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PanturrilhaEsquerda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Pescoco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Quadril")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ToraxContrai")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ToraxRelax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TreinadorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinadorId");

                    b.ToTable("AvaliacoesFisicas");
                });

            modelBuilder.Entity("BulkingPro.Models.CategoriaMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CategoriasMusculares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Superior"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Inferior"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Aeróbico"
                        });
                });

            modelBuilder.Entity("BulkingPro.Models.ComentarioTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Lido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TreinoExercicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinoExercicioId");

                    b.ToTable("ComentariosTreino");
                });

            modelBuilder.Entity("BulkingPro.Models.ExecucaoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<int?>("EsforcoPercebido")
                        .HasColumnType("int");

                    b.Property<string>("ObservacoesGerais")
                        .HasColumnType("longtext");

                    b.Property<int>("TreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinoId");

                    b.ToTable("ExecucoesTreino");
                });

            modelBuilder.Entity("BulkingPro.Models.ExecucaoTreinoExercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaUsada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ExecucaoTreinoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("RepeticoesFeitas")
                        .HasColumnType("longtext");

                    b.Property<int?>("SeriesFeitas")
                        .HasColumnType("int");

                    b.Property<int>("TreinoExercicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExecucaoTreinoId");

                    b.HasIndex("TreinoExercicioId");

                    b.ToTable("ExecucoesTreinoExercicios");
                });

            modelBuilder.Entity("BulkingPro.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int");

                    b.Property<string>("InstrucoesExecucao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("TipoExecucao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("Exercicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício clássico para peitoral",
                            GrupoMuscularId = 1,
                            InstrucoesExecucao = "Deite no banco, desça a barra até o peito e empurre.",
                            Nome = "Supino Reto com Barra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Foco na parte superior do peitoral",
                            GrupoMuscularId = 1,
                            InstrucoesExecucao = "Banco inclinado a 45°, mesmo movimento do supino reto.",
                            Nome = "Supino Inclinado com Barra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Maior amplitude de movimento",
                            GrupoMuscularId = 1,
                            InstrucoesExecucao = "Desça os halteres até sentir o alongamento e empurre.",
                            Nome = "Supino com Halteres",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isolamento do peitoral",
                            GrupoMuscularId = 1,
                            InstrucoesExecucao = "Puxe os cabos em arco na frente do corpo.",
                            Nome = "Crossover",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isolamento peitoral na máquina",
                            GrupoMuscularId = 1,
                            InstrucoesExecucao = "Una os braços à frente contraindo o peitoral.",
                            Nome = "Peck Deck (Borboleta)",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício com peso corporal",
                            GrupoMuscularId = 1,
                            InstrucoesExecucao = "Corpo reto, desça o peito até próximo ao chão.",
                            Nome = "Flexão de Braço",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dorsais e bíceps",
                            GrupoMuscularId = 2,
                            InstrucoesExecucao = "Puxe a barra até a altura do queixo.",
                            Nome = "Puxada Frente",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Espessura das costas",
                            GrupoMuscularId = 2,
                            InstrucoesExecucao = "Curvado, puxe a barra em direção ao abdômen.",
                            Nome = "Remada Curvada",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Trabalha os dorsais isoladamente",
                            GrupoMuscularId = 2,
                            InstrucoesExecucao = "Apoie um joelho no banco, puxe o halter.",
                            Nome = "Remada Unilateral",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ênfase na parte baixa das costas",
                            GrupoMuscularId = 2,
                            InstrucoesExecucao = "Use o triângulo no cabo e puxe até o abdômen.",
                            Nome = "Puxada Triângulo",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício com peso corporal",
                            GrupoMuscularId = 2,
                            InstrucoesExecucao = "Puxe o corpo até o queixo ultrapassar a barra.",
                            Nome = "Barra Fixa",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício composto para costas",
                            GrupoMuscularId = 2,
                            InstrucoesExecucao = "Levante a barra do chão com as costas retas.",
                            Nome = "Levantamento Terra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício básico de bíceps",
                            GrupoMuscularId = 3,
                            InstrucoesExecucao = "Curl com barra reta mantendo os cotovelos fixos.",
                            Nome = "Rosca Direta com Barra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bíceps com halteres alternando",
                            GrupoMuscularId = 3,
                            InstrucoesExecucao = "Curl com halteres alternando os braços.",
                            Nome = "Rosca Alternada",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isolamento do bíceps",
                            GrupoMuscularId = 3,
                            InstrucoesExecucao = "Cotovelo apoiado na coxa, faça o curl.",
                            Nome = "Rosca Concentrada",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bíceps no banco scott",
                            GrupoMuscularId = 3,
                            InstrucoesExecucao = "Braços apoiados no banco inclinado.",
                            Nome = "Rosca Scott",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isolamento do tríceps no cabo",
                            GrupoMuscularId = 4,
                            InstrucoesExecucao = "Puxe a corda para baixo abrindo as pontas.",
                            Nome = "Tríceps Corda",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício com barra para tríceps",
                            GrupoMuscularId = 4,
                            InstrucoesExecucao = "Deite, abaixe a barra até a testa e empurre.",
                            Nome = "Tríceps Testa",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Haltere sobre a cabeça",
                            GrupoMuscularId = 4,
                            InstrucoesExecucao = "Segure halter, abaixe atrás da cabeça.",
                            Nome = "Tríceps Francês",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Peso corporal para tríceps",
                            GrupoMuscularId = 4,
                            InstrucoesExecucao = "Desça entre as barras paralelas e empurre.",
                            Nome = "Mergulho (Paralelas)",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício composto para ombros",
                            GrupoMuscularId = 5,
                            InstrucoesExecucao = "Empurre a barra acima da cabeça.",
                            Nome = "Desenvolvimento com Barra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Feixe médio do deltoide",
                            GrupoMuscularId = 5,
                            InstrucoesExecucao = "Eleve os halteres lateralmente até a altura dos ombros.",
                            Nome = "Elevação Lateral",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Feixe anterior do deltoide",
                            GrupoMuscularId = 5,
                            InstrucoesExecucao = "Eleve os halteres à frente até a altura dos ombros.",
                            Nome = "Elevação Frontal",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Feixe posterior do deltoide",
                            GrupoMuscularId = 5,
                            InstrucoesExecucao = "Curvado, abra os braços para trás.",
                            Nome = "Crucifixo Invertido",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Estabilização do core",
                            GrupoMuscularId = 6,
                            InstrucoesExecucao = "Mantenha o corpo reto apoiado nos antebraços.",
                            Nome = "Prancha",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Crunch básico",
                            GrupoMuscularId = 6,
                            InstrucoesExecucao = "Eleve o tronco contraindo o abdômen.",
                            Nome = "Abdominal Supra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Elevação de pernas",
                            GrupoMuscularId = 6,
                            InstrucoesExecucao = "Deitado, eleve as pernas estendidas.",
                            Nome = "Abdominal Infra",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Abdominal em máquina",
                            GrupoMuscularId = 6,
                            InstrucoesExecucao = "Flexione o tronco na máquina de forma controlada.",
                            Nome = "Abdominal Máquina",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Exercício composto para pernas",
                            GrupoMuscularId = 7,
                            InstrucoesExecucao = "Pés na largura dos ombros, desça até 90°.",
                            Nome = "Agachamento Livre",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Quadríceps e glúteos",
                            GrupoMuscularId = 7,
                            InstrucoesExecucao = "Empurre a plataforma sem travar os joelhos.",
                            Nome = "Leg Press 45°",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isolamento do quadríceps",
                            GrupoMuscularId = 7,
                            InstrucoesExecucao = "Estenda os joelhos na máquina de forma controlada.",
                            Nome = "Cadeira Extensora",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isquiotibiais",
                            GrupoMuscularId = 7,
                            InstrucoesExecucao = "Flexione os joelhos puxando os calcanhares.",
                            Nome = "Mesa Flexora",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Quadríceps e glúteos",
                            GrupoMuscularId = 7,
                            InstrucoesExecucao = "Dê um passo à frente e desça o joelho traseiro.",
                            Nome = "Avanço (Lunge)",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isquiotibiais e glúteos",
                            GrupoMuscularId = 7,
                            InstrucoesExecucao = "Incline o tronco com as pernas semi-estendidas.",
                            Nome = "Stiff",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Glúteo máximo",
                            GrupoMuscularId = 8,
                            InstrucoesExecucao = "Apoie os ombros no banco e empurre o quadril.",
                            Nome = "Elevação Pélvica (Hip Thrust)",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Glúteo médio na máquina",
                            GrupoMuscularId = 8,
                            InstrucoesExecucao = "Abra as pernas contra a resistência.",
                            Nome = "Abdução de Quadril",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Isolamento do glúteo",
                            GrupoMuscularId = 8,
                            InstrucoesExecucao = "Coloque o cabo no tornozelo e estenda a perna para trás.",
                            Nome = "Glúteo no Cabo",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Panturrilha em pé",
                            GrupoMuscularId = 9,
                            InstrucoesExecucao = "Eleve os calcanhares o máximo possível.",
                            Nome = "Gêmeos em Pé",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sóleo (panturrilha sentado)",
                            GrupoMuscularId = 9,
                            InstrucoesExecucao = "Na máquina sentado, eleve os calcanhares.",
                            Nome = "Gêmeos Sentado",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cardio na esteira",
                            GrupoMuscularId = 10,
                            InstrucoesExecucao = "Caminhe ou corra em ritmo moderado.",
                            Nome = "Esteira",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 41,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cardio de baixo impacto",
                            GrupoMuscularId = 10,
                            InstrucoesExecucao = "Pedale em cadência constante.",
                            Nome = "Bicicleta Ergométrica",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 42,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cardio com baixo impacto articular",
                            GrupoMuscularId = 10,
                            InstrucoesExecucao = "Movimento elíptico contínuo.",
                            Nome = "Elíptico",
                            TipoExecucao = 0
                        },
                        new
                        {
                            Id = 43,
                            Ativo = true,
                            DataCriacao = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cardio de alta intensidade",
                            GrupoMuscularId = 10,
                            InstrucoesExecucao = "Pule a corda em ritmo constante.",
                            Nome = "Corda (Jump Rope)",
                            TipoExecucao = 0
                        });
                });

            modelBuilder.Entity("BulkingPro.Models.GrupoMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaMuscularId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaMuscularId");

                    b.ToTable("GruposMusculares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaMuscularId = 1,
                            Nome = "Peito"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaMuscularId = 1,
                            Nome = "Costas"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaMuscularId = 1,
                            Nome = "Bíceps"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaMuscularId = 1,
                            Nome = "Tríceps"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaMuscularId = 1,
                            Nome = "Ombro"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaMuscularId = 1,
                            Nome = "Abdômen"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaMuscularId = 2,
                            Nome = "Perna"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaMuscularId = 2,
                            Nome = "Glúteo"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaMuscularId = 2,
                            Nome = "Panturrilha"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaMuscularId = 3,
                            Nome = "Cardio"
                        });
                });

            modelBuilder.Entity("BulkingPro.Models.HorarioTrabalhoPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("HorariosTrabalhoPersonal");
                });

            modelBuilder.Entity("BulkingPro.Models.PlanoTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlunoId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Objetivo")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<string>("TreinadorId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TreinadorId");

                    b.ToTable("PlanosTreino");
                });

            modelBuilder.Entity("BulkingPro.Models.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("OrdemDia")
                        .HasColumnType("int");

                    b.Property<int>("PlanoTreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanoTreinoId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("BulkingPro.Models.TreinoExercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CargaPlanejada")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("RepeticoesPlanejadas")
                        .HasColumnType("longtext");

                    b.Property<int>("SeriesPlanejadas")
                        .HasColumnType("int");

                    b.Property<int?>("TempoDescanso")
                        .HasColumnType("int");

                    b.Property<int?>("TempoExecucaoSegundos")
                        .HasColumnType("int");

                    b.Property<int>("TreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId");

                    b.HasIndex("TreinoId");

                    b.ToTable("TreinoExercicios");
                });

            modelBuilder.Entity("BulkingPro.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BulkingPro.Models.AgendamentoAluno", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.HorarioTrabalhoPersonal", "HorarioTrabalho")
                        .WithMany()
                        .HasForeignKey("HorarioTrabalhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.Usuario", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("HorarioTrabalho");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("BulkingPro.Models.AlunoHorarioAtendimento", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany("HorariosAtendimento")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.Usuario", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("BulkingPro.Models.AnamneseAluno", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.Usuario", "Treinador")
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("BulkingPro.Models.AvaliacaoFisica", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.Usuario", "Treinador")
                        .WithMany()
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("BulkingPro.Models.ComentarioTreino", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.TreinoExercicio", "TreinoExercicio")
                        .WithMany()
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("TreinoExercicio");
                });

            modelBuilder.Entity("BulkingPro.Models.ExecucaoTreino", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BulkingPro.Models.Treino", "Treino")
                        .WithMany("Execucoes")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("BulkingPro.Models.ExecucaoTreinoExercicio", b =>
                {
                    b.HasOne("BulkingPro.Models.ExecucaoTreino", "ExecucaoTreino")
                        .WithMany("Exercicios")
                        .HasForeignKey("ExecucaoTreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.TreinoExercicio", "TreinoExercicio")
                        .WithMany("Execucoes")
                        .HasForeignKey("TreinoExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExecucaoTreino");

                    b.Navigation("TreinoExercicio");
                });

            modelBuilder.Entity("BulkingPro.Models.Exercicio", b =>
                {
                    b.HasOne("BulkingPro.Models.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Exercicios")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("BulkingPro.Models.GrupoMuscular", b =>
                {
                    b.HasOne("BulkingPro.Models.CategoriaMuscular", "CategoriaMuscular")
                        .WithMany("Grupos")
                        .HasForeignKey("CategoriaMuscularId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaMuscular");
                });

            modelBuilder.Entity("BulkingPro.Models.HorarioTrabalhoPersonal", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("BulkingPro.Models.PlanoTreino", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", "Aluno")
                        .WithMany("PlanosComoAluno")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BulkingPro.Models.Usuario", "Treinador")
                        .WithMany("PlanosComoTreinador")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Aluno");

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("BulkingPro.Models.Treino", b =>
                {
                    b.HasOne("BulkingPro.Models.PlanoTreino", "PlanoTreino")
                        .WithMany("Treinos")
                        .HasForeignKey("PlanoTreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanoTreino");
                });

            modelBuilder.Entity("BulkingPro.Models.TreinoExercicio", b =>
                {
                    b.HasOne("BulkingPro.Models.Exercicio", "Exercicio")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.Treino", "Treino")
                        .WithMany("TreinoExercicios")
                        .HasForeignKey("TreinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulkingPro.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BulkingPro.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BulkingPro.Models.CategoriaMuscular", b =>
                {
                    b.Navigation("Grupos");
                });

            modelBuilder.Entity("BulkingPro.Models.ExecucaoTreino", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("BulkingPro.Models.Exercicio", b =>
                {
                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("BulkingPro.Models.GrupoMuscular", b =>
                {
                    b.Navigation("Exercicios");
                });

            modelBuilder.Entity("BulkingPro.Models.PlanoTreino", b =>
                {
                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("BulkingPro.Models.Treino", b =>
                {
                    b.Navigation("Execucoes");

                    b.Navigation("TreinoExercicios");
                });

            modelBuilder.Entity("BulkingPro.Models.TreinoExercicio", b =>
                {
                    b.Navigation("Execucoes");
                });

            modelBuilder.Entity("BulkingPro.Models.Usuario", b =>
                {
                    b.Navigation("HorariosAtendimento");

                    b.Navigation("PlanosComoAluno");

                    b.Navigation("PlanosComoTreinador");
                });
#pragma warning restore 612, 618
        }
    }
}
